# Generated by Django 5.2.5 on 2025-09-02 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Group', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('level_title', models.CharField(default='No Title', max_length=100)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.group')),
                ('pre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.level')),
            ],
        ),
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('acc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('acc_name', models.CharField(max_length=100)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.level')),
            ],
        ),
    ]
