# Generated by Django 4.2 on 2025-09-02 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('lev_id', models.AutoField(primary_key=True, serialize=False)),
                ('lev_title', models.CharField(max_length=50)),
                ('pre_id', models.IntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.group')),
            ],
        ),
        migrations.CreateModel(
            name='AccountMaster',
            fields=[
                ('acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('acc_title', models.CharField(max_length=100)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.level')),
            ],
        ),
    ]
