# Generated by Django 5.2.5 on 2025-09-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_level_level_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
